#!/bin/bash
# setup-toolchain.sh
# Quick setup script for GCC 9.3.0 toolchain

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TOOLCHAIN_ARCHIVE="$SCRIPT_DIR/gcc-9.3.0-qnx8.tar.gz"

echo ""
echo "=========================================================="
echo "  GCC 9.3.0 QNX 8 Toolchain Setup for BerryCore"
echo "=========================================================="
echo ""

# Check if toolchain archive exists
if [ ! -f "$TOOLCHAIN_ARCHIVE" ]; then
    echo "❌ Error: Toolchain archive not found!"
    echo "   Expected: $TOOLCHAIN_ARCHIVE"
    exit 1
fi

# Prompt for installation directory
echo "Where would you like to install the toolchain?"
echo "Default: ~/berrycore-toolchain"
echo ""
read -p "Installation directory [~/berrycore-toolchain]: " INSTALL_DIR

if [ -z "$INSTALL_DIR" ]; then
    INSTALL_DIR="$HOME/berrycore-toolchain"
fi

# Expand ~ if present
INSTALL_DIR="${INSTALL_DIR/#\~/$HOME}"

echo ""
echo "Installation directory: $INSTALL_DIR"
echo ""

# Check if directory exists
if [ -d "$INSTALL_DIR/gcc-9.3.0-berrycore" ]; then
    echo "⚠ Warning: Toolchain already exists at $INSTALL_DIR/gcc-9.3.0-berrycore"
    read -p "Do you want to overwrite it? [y/N]: " OVERWRITE
    if [ "$OVERWRITE" != "y" ] && [ "$OVERWRITE" != "Y" ]; then
        echo "Installation cancelled."
        exit 0
    fi
    rm -rf "$INSTALL_DIR/gcc-9.3.0-berrycore"
fi

# Create installation directory
mkdir -p "$INSTALL_DIR"

echo "📦 Extracting toolchain..."
echo "   This may take a few minutes..."
echo ""

tar -xzf "$TOOLCHAIN_ARCHIVE" -C "$INSTALL_DIR"

if [ ! -d "$INSTALL_DIR/gcc-9.3.0-berrycore" ]; then
    echo "❌ Error: Extraction failed!"
    exit 1
fi

echo "✓ Toolchain extracted successfully"
echo ""

# Create environment setup script
ENV_SCRIPT="$INSTALL_DIR/qnx-env.sh"

cat > "$ENV_SCRIPT" << EOF
#!/bin/bash
# GCC 9.3.0 Toolchain Environment for BerryCore
# Auto-generated by setup-toolchain.sh

# Toolchain Configuration
export TOOLCHAIN_ROOT="$INSTALL_DIR/gcc-9.3.0-berrycore"
export QNX_TARGET="\$TOOLCHAIN_ROOT"
export QNX_HOST="\$TOOLCHAIN_ROOT"
export QNX_ABI="arm-blackberry-qnx8eabi"

# Compiler Tools
export PATH="\$TOOLCHAIN_ROOT/bin:\$PATH"
export LD_LIBRARY_PATH="\$TOOLCHAIN_ROOT/lib:\$LD_LIBRARY_PATH"

# Build Configuration
export CC="arm-blackberry-qnx8eabi-gcc"
export CXX="arm-blackberry-qnx8eabi-g++"
export AR="arm-blackberry-qnx8eabi-ar"
export RANLIB="arm-blackberry-qnx8eabi-ranlib"
export LD="arm-blackberry-qnx8eabi-ld"
export STRIP="arm-blackberry-qnx8eabi-strip"
export OBJDUMP="arm-blackberry-qnx8eabi-objdump"
export OBJCOPY="arm-blackberry-qnx8eabi-objcopy"
export AS="arm-blackberry-qnx8eabi-as"

# Compiler Flags
export CFLAGS="-march=armv7-a -mfpu=neon -O2"
export CXXFLAGS="-march=armv7-a -mfpu=neon -O2 -std=c++17"
export LDFLAGS="-L\$TOOLCHAIN_ROOT/lib"

# pkg-config
export PKG_CONFIG_PATH="\$TOOLCHAIN_ROOT/lib/pkgconfig:\$PKG_CONFIG_PATH"

# Silence activation message unless explicitly verbose
if [ "\$BERRYCORE_TOOLCHAIN_VERBOSE" = "1" ]; then
    echo "✓ GCC 9.3.0 Toolchain environment loaded"
    echo "  Compiler: \$(arm-blackberry-qnx8eabi-gcc --version 2>/dev/null | head -1)"
    echo "  Target: \$QNX_ABI"
fi
EOF

chmod +x "$ENV_SCRIPT"

echo "✓ Environment script created: $ENV_SCRIPT"
echo ""

# Test the toolchain
echo "🧪 Testing toolchain..."
source "$ENV_SCRIPT"

if ! command -v arm-blackberry-qnx8eabi-gcc &> /dev/null; then
    echo "❌ Error: Toolchain test failed!"
    echo "   GCC compiler not found in PATH"
    exit 1
fi

GCC_VERSION=$(arm-blackberry-qnx8eabi-gcc --version 2>/dev/null | head -1)
echo "✓ Toolchain test passed"
echo "  $GCC_VERSION"
echo ""

# Create a simple test
TEST_DIR="/tmp/berrycore-toolchain-test-$$"
mkdir -p "$TEST_DIR"

cat > "$TEST_DIR/test.c" << 'EOF'
#include <stdio.h>
int main() {
    printf("BerryCore Toolchain Test: SUCCESS\n");
    return 0;
}
EOF

if arm-blackberry-qnx8eabi-gcc "$TEST_DIR/test.c" -o "$TEST_DIR/test" 2>/dev/null; then
    echo "✓ Compilation test passed"
    file "$TEST_DIR/test" | grep -q "ARM" && echo "✓ Binary architecture verified (ARM)"
else
    echo "⚠ Warning: Compilation test failed"
    echo "  The toolchain was installed but a simple test compilation failed."
fi

rm -rf "$TEST_DIR"
echo ""

# Setup instructions
echo "=========================================================="
echo "  Installation Complete!"
echo "=========================================================="
echo ""
echo "📍 Toolchain Location:"
echo "   $INSTALL_DIR/gcc-9.3.0-berrycore"
echo ""
echo "🔧 To use the toolchain, run:"
echo "   source $ENV_SCRIPT"
echo ""
echo "💡 To make it permanent, add this to your ~/.bashrc:"
echo "   echo 'source $ENV_SCRIPT' >> ~/.bashrc"
echo ""
echo "📚 For detailed usage instructions, see:"
echo "   $SCRIPT_DIR/INTEGRATION_GUIDE.md"
echo ""
echo "🚀 Quick test:"
echo "   source $ENV_SCRIPT"
echo "   arm-blackberry-qnx8eabi-gcc --version"
echo ""
echo "=========================================================="
echo ""

