#!/usr/bin/env python3.2
import sys
import os
import subprocess
from urllib.request import urlopen

toolsdir = os.environ.get('NATIVE_TOOLS')
toolsurl = os.environ.get('NATIVE_TOOLS_URL')
# make sure we can proceed
if toolsdir == None:
    print("No NATIVE_TOOLS in environment. Exiting")
    sys.exit(1)

# find the package .zip
pkgname = sys.argv[1]
pkgpath = False
if os.path.isfile(pkgname):
    pkgpath = os.path.abspath(pkgname)

if not pkgpath:
    print('No package ' + pkgname + ' found. Exiting')
    sys.exit(1)

# cd to the toolsdir 
print('Unpacking ' + pkgpath + ' into ' + toolsdir)
os.chdir(toolsdir)
rc = subprocess.call(['unzip', '-uo', pkgpath])
if rc != 0:
    sys.exit(rc)

# Record install stamp for upgrade mode (install.sh reads .berrycore_pkg_stamps/)
try:
    stamp_dir = os.path.join(toolsdir, '.berrycore_pkg_stamps')
    if not os.path.isdir(stamp_dir):
        os.makedirs(stamp_dir)
    pkg_base = os.path.basename(pkgpath)
    if pkg_base.endswith('.zip'):
        pkg_base = pkg_base[:-4]
    mtime = int(os.path.getmtime(pkgpath))
    stamp_path = os.path.join(stamp_dir, pkg_base)
    with open(stamp_path, 'w') as f:
        f.write(str(mtime))
except (OSError, IOError):
    pass

print('Done')
